dist: trusty
sudo: required
language: node_js
node_js:
  - "8.0.0"
os:
  - linux

addons:
  chrome: stable
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
- npm install

script:
  - npm run build
  - npm run preinstall

deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master
# os:
#   - linux
#
# env:
#   global:
#     - DBUS_SESSION_BUS_ADDRESS=/dev/null
#     - DISPLAY=:99.0
#     - CHROME_BIN=chromium-browser
# before_script:
#   - sh -e /etc/init.d/xvfb start
# install:
#   - npm install
# script:
#   - npm run lint
#   - npm run test:once
#   - npm run e2e
